print("Choose a number of money between 1-10")
print("Don't tell anyone how much money you have")
Ready = input ("Ok? ")
print("You get the same amount of money from your friend")
Ready = input ("Are you ready? ")
print("I give you 2k more")
Ready = input ("Calculate ")
print("You give the half amount of money to a help-organization")
Ready = input ("Calculate correctly! ")
print("Give your friend back the money he gave you")
Ready = input ("Be ready for an answer ")
print("You got 1000, left!")
print("Am I correct? ")
